variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

stages:
  - prettier
  - eslint
  - build
  - deploy

prettier:
  stage: prettier
  before_script:
    - yarn install
    - node -v
    - yarn -v
  script: yarn lint:prettier

eslint:
  stage: eslint
  before_script:
    - yarn install
    - node -v
    - yarn -v
  needs:
    - job: prettier
  script: yarn lint:eslint

docker-build:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "IMAGE_APP_TAG=$IMAGE_TAG" >> .env
    - >
      if [ "$CI_COMMIT_REF_NAME" == "master" ]; then
        docker-compose down -v
        docker image rm ${IMAGE_TAG}
      fi
    - docker-compose build --pull
    - docker-compose push
    - docker image rm ${IMAGE_TAG}
    - docker logout
deploy-docker:
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "IMAGE_APP_TAG=$IMAGE_TAG" >> .env
    - docker-compose down -v
    - docker image rm ${IMAGE_TAG}
    - docker-compose pull
    - docker-compose up -d
    - docker logout
  only:
    - master
