variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

stages:
  - prettier
  - eslint
  - build

prettier:
  stage: prettier
  before_script:
    - yarn install
    - node -v
    - yarn -v
  script: yarn lint:prettier

eslint:
  stage: eslint
  before_script:
    - yarn install
    - node -v
    - yarn -v
  needs:
    - job: prettier
  script: yarn lint:eslint

docker-build:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "IMAGE_APP_TAG=$IMAGE_TAG" >> .env
    - docker-compose build --pull
    - >
      if [ "$CI_COMMIT_REF_NAME" == "master" ]; then
        docker-compose down -v
      fi
    - docker-compose push
    - >
      if [ "$CI_COMMIT_REF_NAME" == "master" ]; then
        docker-compose pull
        docker-compose up -d
       else
        docker image rm ${IMAGE_TAG}
      fi
    - docker logout
