before_script:
  - yarn install
  - node -v
  - yarn -v

stages:
  - prettier
  - eslint

prettier:
  stage: prettier
  script: yarn lint:prettier

eslint:
  stage: eslint
  needs:
    - job: prettier
  script: yarn lint:eslint
