version: "3.7"

services:
  ui:
    image: ${IMAGE_APP_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: charity_ui
    ports:
      - "80:80"
      - "7778:7778"
    environment:
      - REACT_APP_API_URL=http://api:9000
networks:
  default:
    external:
      name: charity-network
