version: "3.7"

services:
  ui:
    image: ${IMAGE_APP_TAG}
    build:
      context: .
      dockerfile: Dockerfile-master
    container_name: charity_ui
    ports:
      - "7999:7999"
      - "7778:7778"
    environment:
      - REACT_APP_API_URL=http://api:9000
      - NODE_OPTIONS=--max_old_space_size=4096
      - NODE_ENV=production
networks:
  default:
    external:
      name: charity-network
