/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { AuthEmailConfirmationInput } from '../models';
// @ts-ignore
import { AuthRegistrationInput } from '../models';
/**
 * RegistrationApi - axios parameter creator
 * @export
 */
export const RegistrationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Confirms email with code from email
         * @summary Confirm email
         * @param {AuthEmailConfirmationInput} request Email confirmation input
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerConfirmPost: async (request: AuthEmailConfirmationInput, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            if (request === null || request === undefined) {
                throw new RequiredError('request','Required parameter request was null or undefined when calling registerConfirmPost.');
            }
            const localVarPath = `/register/confirm`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const nonString = typeof request !== 'string';
            const needsSerialization = nonString && configuration && configuration.isJsonMime
                ? configuration.isJsonMime(localVarRequestOptions.headers['Content-Type'])
                : nonString;
            localVarRequestOptions.data =  needsSerialization
                ? JSON.stringify(request !== undefined ? request : {})
                : (request || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Register with this route
         * @summary Register
         * @param {AuthRegistrationInput} request Email registration input
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerPost: async (request: AuthRegistrationInput, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            if (request === null || request === undefined) {
                throw new RequiredError('request','Required parameter request was null or undefined when calling registerPost.');
            }
            const localVarPath = `/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const nonString = typeof request !== 'string';
            const needsSerialization = nonString && configuration && configuration.isJsonMime
                ? configuration.isJsonMime(localVarRequestOptions.headers['Content-Type'])
                : nonString;
            localVarRequestOptions.data =  needsSerialization
                ? JSON.stringify(request !== undefined ? request : {})
                : (request || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RegistrationApi - functional programming interface
 * @export
 */
export const RegistrationApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Confirms email with code from email
         * @summary Confirm email
         * @param {AuthEmailConfirmationInput} request Email confirmation input
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerConfirmPost(request: AuthEmailConfirmationInput, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await RegistrationApiAxiosParamCreator(configuration).registerConfirmPost(request, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Register with this route
         * @summary Register
         * @param {AuthRegistrationInput} request Email registration input
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerPost(request: AuthRegistrationInput, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await RegistrationApiAxiosParamCreator(configuration).registerPost(request, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * RegistrationApi - factory interface
 * @export
 */
export const RegistrationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Confirms email with code from email
         * @summary Confirm email
         * @param {AuthEmailConfirmationInput} request Email confirmation input
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerConfirmPost(request: AuthEmailConfirmationInput, options?: any): AxiosPromise<void> {
            return RegistrationApiFp(configuration).registerConfirmPost(request, options).then((request) => request(axios, basePath));
        },
        /**
         * Register with this route
         * @summary Register
         * @param {AuthRegistrationInput} request Email registration input
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerPost(request: AuthRegistrationInput, options?: any): AxiosPromise<void> {
            return RegistrationApiFp(configuration).registerPost(request, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for registerConfirmPost operation in RegistrationApi.
 * @export
 * @interface RegistrationApiRegisterConfirmPostRequest
 */
export interface RegistrationApiRegisterConfirmPostRequest {
    /**
     * Email confirmation input
     * @type {AuthEmailConfirmationInput}
     * @memberof RegistrationApiRegisterConfirmPost
     */
    readonly request: AuthEmailConfirmationInput
}

/**
 * Request parameters for registerPost operation in RegistrationApi.
 * @export
 * @interface RegistrationApiRegisterPostRequest
 */
export interface RegistrationApiRegisterPostRequest {
    /**
     * Email registration input
     * @type {AuthRegistrationInput}
     * @memberof RegistrationApiRegisterPost
     */
    readonly request: AuthRegistrationInput
}

/**
 * RegistrationApi - object-oriented interface
 * @export
 * @class RegistrationApi
 * @extends {BaseAPI}
 */
export class RegistrationApi extends BaseAPI {
    /**
     * Confirms email with code from email
     * @summary Confirm email
     * @param {RegistrationApiRegisterConfirmPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RegistrationApi
     */
    public registerConfirmPost(requestParameters: RegistrationApiRegisterConfirmPostRequest, options?: any) {
        return RegistrationApiFp(this.configuration).registerConfirmPost(requestParameters.request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Register with this route
     * @summary Register
     * @param {RegistrationApiRegisterPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RegistrationApi
     */
    public registerPost(requestParameters: RegistrationApiRegisterPostRequest, options?: any) {
        return RegistrationApiFp(this.configuration).registerPost(requestParameters.request, options).then((request) => request(this.axios, this.basePath));
    }
}
