/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AnalyticsTopCategory
 */
export interface AnalyticsTopCategory {
    /**
     * 
     * @type {string}
     * @memberof AnalyticsTopCategory
     */
    category_id?: string;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsTopCategory
     */
    count?: number;
}


