/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AnalyticsOneMonthProfit
 */
export interface AnalyticsOneMonthProfit {
    /**
     * 
     * @type {string}
     * @memberof AnalyticsOneMonthProfit
     */
    month?: string;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsOneMonthProfit
     */
    to_application?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsOneMonthProfit
     */
    to_fund?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsOneMonthProfit
     */
    total?: number;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsOneMonthProfit
     */
    year?: string;
}


