/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UserUser } from './user-user';

/**
 * 
 * @export
 * @interface AuditAudit
 */
export interface AuditAudit {
    /**
     * 
     * @type {UserUser}
     * @memberof AuditAudit
     */
    author?: UserUser;
    /**
     * 
     * @type {string}
     * @memberof AuditAudit
     */
    created_at?: string;
    /**
     * 
     * @type {string}
     * @memberof AuditAudit
     */
    data?: string;
    /**
     * 
     * @type {string}
     * @memberof AuditAudit
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AuditAudit
     */
    type?: AuditAuditTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum AuditAuditTypeEnum {
    Login = 'Login',
    ApplicationStatusChanged = 'ApplicationStatusChanged',
    ApplicationDataChange = 'ApplicationDataChange'
}



