/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthRegistrationInput
 */
export interface AuthRegistrationInput {
    /**
     * 
     * @type {string}
     * @memberof AuthRegistrationInput
     */
    birth_date?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthRegistrationInput
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthRegistrationInput
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthRegistrationInput
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AuthRegistrationInput
     */
    first_name: string;
    /**
     * 
     * @type {string}
     * @memberof AuthRegistrationInput
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthRegistrationInput
     */
    last_name: string;
    /**
     * 
     * @type {string}
     * @memberof AuthRegistrationInput
     */
    middle_name?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthRegistrationInput
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof AuthRegistrationInput
     */
    phone?: string;
}


