/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BlockchainStatus
 */
export interface BlockchainStatus {
    /**
     * 
     * @type {string}
     * @memberof BlockchainStatus
     */
    batch_id?: string;
    /**
     * 
     * @type {string}
     * @memberof BlockchainStatus
     */
    created_at?: string;
    /**
     * 
     * @type {string}
     * @memberof BlockchainStatus
     */
    error_string?: string;
    /**
     * 
     * @type {string}
     * @memberof BlockchainStatus
     */
    status?: BlockchainStatusStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BlockchainStatus
     */
    type?: BlockchainStatusTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof BlockchainStatus
     */
    updated_at?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum BlockchainStatusStatusEnum {
    Pending = 'Pending',
    Success = 'Success',
    Failure = 'Failure'
}
/**
    * @export
    * @enum {string}
    */
export enum BlockchainStatusTypeEnum {
    DonateToCharity = 'DonateToCharity',
    DonateFromCharityToApplication = 'DonateFromCharityToApplication',
    DonateToCharityFromExistingUser = 'DonateToCharityFromExistingUser',
    DonateToCharityFromNewUser = 'DonateToCharityFromNewUser',
    DepositMoney = 'DepositMoney',
    DonateToApplication = 'DonateToApplication',
    ProposeApplication = 'ProposeApplication',
    PublishApplication = 'PublishApplication',
    CancelApplication = 'CancelApplication',
    Registration = 'Registration',
    CloseApplication = 'CloseApplication'
}



