/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UtilsMoneyJson } from './utils-money-json';

/**
 * 
 * @export
 * @interface BlockchainDeposit
 */
export interface BlockchainDeposit {
    /**
     * 
     * @type {UtilsMoneyJson}
     * @memberof BlockchainDeposit
     */
    amount: UtilsMoneyJson;
    /**
     * 
     * @type {string}
     * @memberof BlockchainDeposit
     */
    user_id: string;
}


