/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DonationRequestDonationRequest } from './donation-request-donation-request';
import { UserUser } from './user-user';
import { UtilsMoneyJson } from './utils-money-json';

/**
 * 
 * @export
 * @interface BlockchainDonation
 */
export interface BlockchainDonation {
    /**
     * 
     * @type {UtilsMoneyJson}
     * @memberof BlockchainDonation
     */
    amount?: UtilsMoneyJson;
    /**
     * 
     * @type {boolean}
     * @memberof BlockchainDonation
     */
    anonymous?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BlockchainDonation
     */
    created_at?: string;
    /**
     * 
     * @type {UserUser}
     * @memberof BlockchainDonation
     */
    donation_author?: UserUser;
    /**
     * 
     * @type {string}
     * @memberof BlockchainDonation
     */
    donation_author_id?: string;
    /**
     * 
     * @type {DonationRequestDonationRequest}
     * @memberof BlockchainDonation
     */
    donation_request?: DonationRequestDonationRequest;
    /**
     * 
     * @type {number}
     * @memberof BlockchainDonation
     */
    donation_request_id?: number;
    /**
     * 
     * @type {string}
     * @memberof BlockchainDonation
     */
    id?: string;
}


