/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CategoryAdminCategory
 */
export interface CategoryAdminCategory {
    /**
     * 
     * @type {string}
     * @memberof CategoryAdminCategory
     */
    ara: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryAdminCategory
     */
    eng: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryAdminCategory
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof CategoryAdminCategory
     */
    is_hidden?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CategoryAdminCategory
     */
    rus: string;
}


