/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CharityFundInfo
 */
export interface CharityFundInfo {
    /**
     * 
     * @type {string}
     * @memberof CharityFundInfo
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof CharityFundInfo
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CharityFundInfo
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CharityFundInfo
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof CharityFundInfo
     */
    title: string;
}


