/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FileInfo } from './file-info';

/**
 * 
 * @export
 * @interface CharityFundInfoResponse
 */
export interface CharityFundInfoResponse {
    /**
     * 
     * @type {string}
     * @memberof CharityFundInfoResponse
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof CharityFundInfoResponse
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CharityFundInfoResponse
     */
    email?: string;
    /**
     * 
     * @type {Array<FileInfo>}
     * @memberof CharityFundInfoResponse
     */
    files?: Array<FileInfo>;
    /**
     * 
     * @type {string}
     * @memberof CharityFundInfoResponse
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof CharityFundInfoResponse
     */
    title?: string;
}


