/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CharityFundInput
 */
export interface CharityFundInput {
    /**
     * 
     * @type {string}
     * @memberof CharityFundInput
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof CharityFundInput
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CharityFundInput
     */
    email?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CharityFundInput
     */
    file_ids?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CharityFundInput
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof CharityFundInput
     */
    title?: string;
}


