/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ChatAdminInput
 */
export interface ChatAdminInput {
    /**
     * 
     * @type {Array<string>}
     * @memberof ChatAdminInput
     */
    attachments?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ChatAdminInput
     */
    body: string;
    /**
     * 
     * @type {string}
     * @memberof ChatAdminInput
     */
    dialog_id: string;
}


