/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ChatDialog } from './chat-dialog';
import { UtilsPageData } from './utils-page-data';

/**
 * 
 * @export
 * @interface ChatDialogResponse
 */
export interface ChatDialogResponse {
    /**
     * 
     * @type {Array<ChatDialog>}
     * @memberof ChatDialogResponse
     */
    data?: Array<ChatDialog>;
    /**
     * 
     * @type {UtilsPageData}
     * @memberof ChatDialogResponse
     */
    page?: UtilsPageData;
}


