/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ChatMessage } from './chat-message';
import { UserUser } from './user-user';

/**
 * 
 * @export
 * @interface ChatDialogResponseBody
 */
export interface ChatDialogResponseBody {
    /**
     * 
     * @type {string}
     * @memberof ChatDialogResponseBody
     */
    id?: string;
    /**
     * 
     * @type {ChatMessage}
     * @memberof ChatDialogResponseBody
     */
    last_message?: ChatMessage;
    /**
     * 
     * @type {number}
     * @memberof ChatDialogResponseBody
     */
    unread_message_counter?: number;
    /**
     * 
     * @type {UserUser}
     * @memberof ChatDialogResponseBody
     */
    user?: UserUser;
}


