/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DonationRequestBody } from './donation-request-body';
import { UtilsPageData } from './utils-page-data';

/**
 * 
 * @export
 * @interface DonationRequestResponse
 */
export interface DonationRequestResponse {
    /**
     * 
     * @type {Array<DonationRequestBody>}
     * @memberof DonationRequestResponse
     */
    data?: Array<DonationRequestBody>;
    /**
     * 
     * @type {UtilsPageData}
     * @memberof DonationRequestResponse
     */
    page?: UtilsPageData;
}


