/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UserUser } from './user-user';

/**
 * 
 * @export
 * @interface DonationRequestStatusHistory
 */
export interface DonationRequestStatusHistory {
    /**
     * 
     * @type {UserUser}
     * @memberof DonationRequestStatusHistory
     */
    assignee?: UserUser;
    /**
     * 
     * @type {UserUser}
     * @memberof DonationRequestStatusHistory
     */
    author?: UserUser;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestStatusHistory
     */
    created_at?: string;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestStatusHistory
     */
    current_status?: string;
    /**
     * 
     * @type {number}
     * @memberof DonationRequestStatusHistory
     */
    donation_request_id?: number;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestStatusHistory
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestStatusHistory
     */
    previous_status?: string;
}


