/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DonationRequestSubmitReviewInput
 */
export interface DonationRequestSubmitReviewInput {
    /**
     * 
     * @type {number}
     * @memberof DonationRequestSubmitReviewInput
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestSubmitReviewInput
     */
    review_status?: DonationRequestSubmitReviewInputReviewStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum DonationRequestSubmitReviewInputReviewStatusEnum {
    Accepted = 'Accepted',
    Rejected = 'Rejected',
    NotViewed = 'NotViewed'
}



