/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UserSimpleUser } from './user-simple-user';

/**
 * 
 * @export
 * @interface DonationRequestInput
 */
export interface DonationRequestInput {
    /**
     * 
     * @type {string}
     * @memberof DonationRequestInput
     */
    assignee_id?: string;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestInput
     */
    description?: string;
    /**
     * 
     * @type {UserSimpleUser}
     * @memberof DonationRequestInput
     */
    donee?: UserSimpleUser;
    /**
     * 
     * @type {Array<string>}
     * @memberof DonationRequestInput
     */
    file_ids?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestInput
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestInput
     */
    relationship?: string;
    /**
     * 
     * @type {number}
     * @memberof DonationRequestInput
     */
    request_amount?: number;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestInput
     */
    request_type?: string;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestInput
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestInput
     */
    until?: string;
}


