/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UserSimpleUser } from './user-simple-user';
import { UserUser } from './user-user';

/**
 * 
 * @export
 * @interface DonationRequestDonationRequest
 */
export interface DonationRequestDonationRequest {
    /**
     * 
     * @type {boolean}
     * @memberof DonationRequestDonationRequest
     */
    anonymous?: boolean;
    /**
     * 
     * @type {number}
     * @memberof DonationRequestDonationRequest
     */
    approved_amount?: number;
    /**
     * 
     * @type {UserUser}
     * @memberof DonationRequestDonationRequest
     */
    assignee?: UserUser;
    /**
     * 
     * @type {UserUser}
     * @memberof DonationRequestDonationRequest
     */
    author?: UserUser;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestDonationRequest
     */
    created_at?: string;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestDonationRequest
     */
    description?: string;
    /**
     * 
     * @type {UserSimpleUser}
     * @memberof DonationRequestDonationRequest
     */
    donee?: UserSimpleUser;
    /**
     * 
     * @type {number}
     * @memberof DonationRequestDonationRequest
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof DonationRequestDonationRequest
     */
    is_private?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestDonationRequest
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestDonationRequest
     */
    relationship?: string;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestDonationRequest
     */
    request_type?: string;
    /**
     * 
     * @type {number}
     * @memberof DonationRequestDonationRequest
     */
    requested_amount?: number;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestDonationRequest
     */
    started_at?: string;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestDonationRequest
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestDonationRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestDonationRequest
     */
    until?: string;
}


