/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UserSimpleUser } from './user-simple-user';
import { UtilsMoneyJson } from './utils-money-json';

/**
 * 
 * @export
 * @interface DonationRequestSuperManagerInput
 */
export interface DonationRequestSuperManagerInput {
    /**
     * 
     * @type {UtilsMoneyJson}
     * @memberof DonationRequestSuperManagerInput
     */
    approved_amount?: UtilsMoneyJson;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestSuperManagerInput
     */
    assignee_id?: string;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestSuperManagerInput
     */
    category_id: string;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestSuperManagerInput
     */
    comment?: string;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestSuperManagerInput
     */
    description?: string;
    /**
     * 
     * @type {UserSimpleUser}
     * @memberof DonationRequestSuperManagerInput
     */
    donee?: UserSimpleUser;
    /**
     * 
     * @type {Array<string>}
     * @memberof DonationRequestSuperManagerInput
     */
    file_ids?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestSuperManagerInput
     */
    relationship?: string;
    /**
     * 
     * @type {UtilsMoneyJson}
     * @memberof DonationRequestSuperManagerInput
     */
    requested_amount?: UtilsMoneyJson;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestSuperManagerInput
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof DonationRequestSuperManagerInput
     */
    until?: string;
}


