/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FileInfo
 */
export interface FileInfo {
    /**
     * 
     * @type {string}
     * @memberof FileInfo
     */
    created_at?: string;
    /**
     * 
     * @type {string}
     * @memberof FileInfo
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof FileInfo
     */
    mime_type?: string;
    /**
     * 
     * @type {string}
     * @memberof FileInfo
     */
    title?: string;
}


