/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModelsUpdateDonationStatusInput
 */
export interface ModelsUpdateDonationStatusInput {
    /**
     * 
     * @type {string}
     * @memberof ModelsUpdateDonationStatusInput
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUpdateDonationStatusInput
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUpdateDonationStatusInput
     */
    user_id?: string;
}


