/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ModelsDonationRequestBody } from './models-donation-request-body';
import { ModelsPageData } from './models-page-data';

/**
 * 
 * @export
 * @interface ModelsDonationRequestResponse
 */
export interface ModelsDonationRequestResponse {
    /**
     * 
     * @type {Array<ModelsDonationRequestBody>}
     * @memberof ModelsDonationRequestResponse
     */
    data?: Array<ModelsDonationRequestBody>;
    /**
     * 
     * @type {ModelsPageData}
     * @memberof ModelsDonationRequestResponse
     */
    page?: ModelsPageData;
}


