/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModelsFileResponse
 */
export interface ModelsFileResponse {
    /**
     * 
     * @type {string}
     * @memberof ModelsFileResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsFileResponse
     */
    id?: string;
}


