/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModelsSimpleUser
 */
export interface ModelsSimpleUser {
    /**
     * 
     * @type {string}
     * @memberof ModelsSimpleUser
     */
    first_name?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsSimpleUser
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsSimpleUser
     */
    last_name?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsSimpleUser
     */
    middle_name?: string;
}


