/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NewsInput
 */
export interface NewsInput {
  /**
   * 
   * @type {string}
   * @memberof NewsInput
   */
  description: string;
  /**
   * 
   * @type {string}
   * @memberof NewsInput
   */
  image_id?: string;
  /**
   * 
   * @type {string}
   * @memberof NewsInput
   */
  text: string;
  /**
   * 
   * @type {string}
   * @memberof NewsInput
   */
  title: string;
}


