/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UserUser } from './user-user';

/**
 * 
 * @export
 * @interface NotificationsNotification
 */
export interface NotificationsNotification {
    /**
     * 
     * @type {string}
     * @memberof NotificationsNotification
     */
    body?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationsNotification
     */
    created_at?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationsNotification
     */
    id?: string;
    /**
     * 
     * @type {UserUser}
     * @memberof NotificationsNotification
     */
    notification_author?: UserUser;
    /**
     * 
     * @type {string}
     * @memberof NotificationsNotification
     */
    notification_type?: string;
}


