/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CategoryCategory } from './category-category';
import { UserPrettyPublicKey } from './user-pretty-public-key';

/**
 * 
 * @export
 * @interface UserExtendedUser
 */
export interface UserExtendedUser {
    /**
     * 
     * @type {Array<CategoryCategory>}
     * @memberof UserExtendedUser
     */
    assigned_categories?: Array<CategoryCategory>;
    /**
     * 
     * @type {string}
     * @memberof UserExtendedUser
     */
    birth_date?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserExtendedUser
     */
    blocked?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserExtendedUser
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof UserExtendedUser
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof UserExtendedUser
     */
    created_at?: string;
    /**
     * 
     * @type {string}
     * @memberof UserExtendedUser
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserExtendedUser
     */
    first_name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserExtendedUser
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserExtendedUser
     */
    image_id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserExtendedUser
     */
    last_name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserExtendedUser
     */
    middle_name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserExtendedUser
     */
    phone?: string;
    /**
     * 
     * @type {UserPrettyPublicKey}
     * @memberof UserExtendedUser
     */
    pretty_public_key?: UserPrettyPublicKey;
    /**
     * 
     * @type {string}
     * @memberof UserExtendedUser
     */
    role?: UserExtendedUserRoleEnum;
    /**
     * 
     * @type {boolean}
     * @memberof UserExtendedUser
     */
    tech_user?: boolean;
}

/**
    * @export
    * @enum {string}
    */
export enum UserExtendedUserRoleEnum {
    User = 'User',
    Manager = 'Manager',
    SuperManager = 'SuperManager',
    ContentManager = 'ContentManager',
    Operator = 'Operator',
    Admin = 'Admin'
}



