/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UtilsMoneyJson
 */
export interface UtilsMoneyJson {
    /**
     * 
     * @type {string}
     * @memberof UtilsMoneyJson
     */
    currency?: string;
    /**
     * 
     * @type {number}
     * @memberof UtilsMoneyJson
     */
    denominator?: number;
    /**
     * 
     * @type {number}
     * @memberof UtilsMoneyJson
     */
    numerator?: number;
}


