/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UtilsPageData
 */
export interface UtilsPageData {
    /**
     * 
     * @type {number}
     * @memberof UtilsPageData
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof UtilsPageData
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof UtilsPageData
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof UtilsPageData
     */
    totalPages?: number;
}


