/* tslint:disable */
/* eslint-disable */
/**
 * Charity API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api/category-api';
export * from './api/charity-api';
export * from './api/donation-request-api';
export * from './api/donations-api';
export * from './api/file-api';
export * from './api/login-api';
export * from './api/money-api';
export * from './api/news-api';
export * from './api/notifications-api';
export * from './api/registration-api';
export * from './api/user-api';

