name: CI

on:
  pull_request:
    branches:
    - master
    - develop
  push:
    branches:
    - master
    - develop

jobs:
  format:
    name: Run eslint & prettier
    runs-on: ubuntu-18.04

    steps:
      - name: yarn install, eslint & prettier
        with:
          run: |
            yarn install
            node -v
            yarn -v
            yarn lint:prettier
            yarn lint:eslint
        
