name: CI

on:
  pull_request:
    branches:
    - develop
  push:
    branches:
    - develop

jobs:
  format:
    name: Run eslint & prettier
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: yarn install, eslint & prettier
        run: |
          yarn install
          node -v
          yarn -v
          yarn lint:prettier
          yarn lint:eslint
        
