name: CI React App

on:
  push:
    branches: 
     - develop
     - master
  pull_request:
    branches: 
    - develop
    - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          yarn install
          node -v
          yarn -v
          yarn lint:prettier
          
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          yarn install
          node -v
          yarn -v
          yarn lint:eslint
