name: CI

on:
  pull_request:
    branches:
    - develop
  push:
    branches:
    - develop

jobs:
  format:
    name: Run eslint & prettier
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: yarn install, eslint & prettier
        run: |
          yarn install
          node -v
          yarn -v
          yarn lint:prettier
          yarn lint:eslint
          
          
  build:
    name: Build project and create artifact
    runs-on: ubuntu-18.04
    
    steps:
     - name: Checkout
       uses: actions/checkout@v2.4.0

     - name: Build project
     - run: |
        yarn install
        node -v
        yarn -v
        yarn build
        ls -al
     - uses: actions/upload-artifact@v2
       with:
          name: my-app
          path: index.js
        
